In [1]:
import torch

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cpu


## Introduction to Tensors

In [4]:
# Creating tensor
# scalar
scalar = torch.tensor(7)
scalar,scalar.shape

(tensor(7), torch.Size([]))

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector.ndim

1

In [12]:
torch.tensor([[7],7])

TypeError: not a sequence

In [13]:
torch.tensor([[7],[7]])

tensor([[7],
        [7]])

In [14]:
vector.shape

torch.Size([2])

In [15]:
# Matrix

MATRIX = torch.tensor([[7,8],[9,10]])

In [17]:
MATRIX.shape, MATRIX.ndim

(torch.Size([2, 2]), 2)

In [18]:
# Creating random tensors in Pytorch

# Create random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6476, 0.9253, 0.6812, 0.8694],
        [0.4808, 0.8946, 0.4895, 0.9447],
        [0.4395, 0.7760, 0.1075, 0.3942]])

In [19]:
# Create a random tensor with the same shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height,width, color chanels
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [20]:
## Creating Zeros and Ones
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [28]:
# Creating range of tensors and tensor like
one_to_ten = torch.arange(start=1,end=100,step=9)
one_to_ten

tensor([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [29]:
zeroes = torch.zeros_like(input= one_to_ten)
zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
# Tensor Datatyp
float32 = torch.tensor([3.0,7.0],
             dtype=None, # Dataype of the tensor
             device="cpu",   # cpu or cuda for gpu 
             requires_grad=False) # whether or not to track gradients

In [34]:
float16 = float32.type(torch.float16)

In [35]:
float32*float16

tensor([ 9., 49.])

In [36]:
# Getting information from the tensor

x = torch.rand((3,4))
x

tensor([[0.4797, 0.3861, 0.9864, 0.2729],
        [0.4566, 0.6463, 0.2049, 0.4103],
        [0.5802, 0.8215, 0.3129, 0.9020]])

In [37]:
x.dtype

torch.float32

In [39]:
x.ndim

2

In [40]:
x.shape

torch.Size([3, 4])

In [42]:
x.device

device(type='cpu')

## Tensor Operations

* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [43]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [44]:
tensor* 10

tensor([10, 20, 30])

In [45]:
tensor - 10

tensor([-9, -8, -7])

In [46]:
# in built pytorch lib
torch.mul(tensor,100)

tensor([100, 200, 300])

In [47]:
torch.add(tensor,99)

tensor([100, 101, 102])

In [48]:
tensor * tensor

tensor([1, 4, 9])

In [49]:
torch.matmul(tensor,tensor)

tensor(14)

In [50]:
tensor @ tensor

tensor(14)

## Tensor Aggregations

In [59]:
x = torch.arange(10,1000,8,dtype=torch.float32)

In [60]:
x.min(),x.max()

(tensor(10.), tensor(994.))

In [62]:
x.mean(),x.std(),x.median(),x.sum()

(tensor(502.), tensor(287.5181), tensor(498.), tensor(62248.))

## Finding pos min max

In [64]:
x

tensor([ 10.,  18.,  26.,  34.,  42.,  50.,  58.,  66.,  74.,  82.,  90.,  98.,
        106., 114., 122., 130., 138., 146., 154., 162., 170., 178., 186., 194.,
        202., 210., 218., 226., 234., 242., 250., 258., 266., 274., 282., 290.,
        298., 306., 314., 322., 330., 338., 346., 354., 362., 370., 378., 386.,
        394., 402., 410., 418., 426., 434., 442., 450., 458., 466., 474., 482.,
        490., 498., 506., 514., 522., 530., 538., 546., 554., 562., 570., 578.,
        586., 594., 602., 610., 618., 626., 634., 642., 650., 658., 666., 674.,
        682., 690., 698., 706., 714., 722., 730., 738., 746., 754., 762., 770.,
        778., 786., 794., 802., 810., 818., 826., 834., 842., 850., 858., 866.,
        874., 882., 890., 898., 906., 914., 922., 930., 938., 946., 954., 962.,
        970., 978., 986., 994.])

In [63]:
x.argmin()

tensor(0)

In [65]:
x.argmax()

tensor(123)

In [66]:
y = torch.rand(size=(10,10))

In [67]:
y

tensor([[0.6934, 0.1856, 0.4122, 0.5733, 0.5629, 0.8431, 0.4227, 0.0805, 0.1287,
         0.1260],
        [0.5956, 0.2613, 0.0645, 0.1867, 0.8577, 0.2373, 0.5850, 0.7072, 0.7411,
         0.7548],
        [0.1414, 0.6033, 0.8414, 0.6895, 0.7259, 0.7961, 0.8480, 0.2117, 0.8694,
         0.6458],
        [0.5724, 0.1950, 0.5324, 0.9193, 0.0010, 0.8864, 0.5690, 0.2220, 0.5129,
         0.9684],
        [0.3073, 0.4840, 0.9024, 0.6007, 0.3589, 0.5309, 0.9908, 0.9017, 0.0859,
         0.6986],
        [0.9019, 0.8740, 0.4117, 0.7350, 0.6134, 0.5744, 0.1982, 0.1449, 0.8375,
         0.1270],
        [0.7762, 0.8905, 0.1029, 0.3630, 0.1813, 0.5578, 0.3215, 0.0277, 0.4926,
         0.7553],
        [0.0532, 0.5250, 0.9852, 0.5247, 0.0914, 0.9879, 0.6500, 0.3194, 0.4113,
         0.9037],
        [0.0782, 0.8570, 0.5367, 0.8785, 0.3825, 0.3678, 0.0756, 0.6938, 0.4409,
         0.7848],
        [0.4694, 0.9719, 0.8797, 0.3441, 0.0730, 0.1423, 0.0487, 0.0955, 0.8552,
         0.7131]])

In [68]:
y.argmin()

tensor(34)

In [77]:
y.reshape((1,100))

tensor([[0.6934, 0.1856, 0.4122, 0.5733, 0.5629, 0.8431, 0.4227, 0.0805, 0.1287,
         0.1260, 0.5956, 0.2613, 0.0645, 0.1867, 0.8577, 0.2373, 0.5850, 0.7072,
         0.7411, 0.7548, 0.1414, 0.6033, 0.8414, 0.6895, 0.7259, 0.7961, 0.8480,
         0.2117, 0.8694, 0.6458, 0.5724, 0.1950, 0.5324, 0.9193, 0.0010, 0.8864,
         0.5690, 0.2220, 0.5129, 0.9684, 0.3073, 0.4840, 0.9024, 0.6007, 0.3589,
         0.5309, 0.9908, 0.9017, 0.0859, 0.6986, 0.9019, 0.8740, 0.4117, 0.7350,
         0.6134, 0.5744, 0.1982, 0.1449, 0.8375, 0.1270, 0.7762, 0.8905, 0.1029,
         0.3630, 0.1813, 0.5578, 0.3215, 0.0277, 0.4926, 0.7553, 0.0532, 0.5250,
         0.9852, 0.5247, 0.0914, 0.9879, 0.6500, 0.3194, 0.4113, 0.9037, 0.0782,
         0.8570, 0.5367, 0.8785, 0.3825, 0.3678, 0.0756, 0.6938, 0.4409, 0.7848,
         0.4694, 0.9719, 0.8797, 0.3441, 0.0730, 0.1423, 0.0487, 0.0955, 0.8552,
         0.7131]])

## Reshaping, stacking, squeezing, unsqueezing

In [80]:
x,x.shape

(tensor([ 10.,  18.,  26.,  34.,  42.,  50.,  58.,  66.,  74.,  82.,  90.,  98.,
         106., 114., 122., 130., 138., 146., 154., 162., 170., 178., 186., 194.,
         202., 210., 218., 226., 234., 242., 250., 258., 266., 274., 282., 290.,
         298., 306., 314., 322., 330., 338., 346., 354., 362., 370., 378., 386.,
         394., 402., 410., 418., 426., 434., 442., 450., 458., 466., 474., 482.,
         490., 498., 506., 514., 522., 530., 538., 546., 554., 562., 570., 578.,
         586., 594., 602., 610., 618., 626., 634., 642., 650., 658., 666., 674.,
         682., 690., 698., 706., 714., 722., 730., 738., 746., 754., 762., 770.,
         778., 786., 794., 802., 810., 818., 826., 834., 842., 850., 858., 866.,
         874., 882., 890., 898., 906., 914., 922., 930., 938., 946., 954., 962.,
         970., 978., 986., 994.]),
 torch.Size([124]))

In [82]:
x_reshaped = x.reshape(4,31)

In [84]:
x_reshaped


tensor([[ 10.,  18.,  26.,  34.,  42.,  50.,  58.,  66.,  74.,  82.,  90.,  98.,
         106., 114., 122., 130., 138., 146., 154., 162., 170., 178., 186., 194.,
         202., 210., 218., 226., 234., 242., 250.],
        [258., 266., 274., 282., 290., 298., 306., 314., 322., 330., 338., 346.,
         354., 362., 370., 378., 386., 394., 402., 410., 418., 426., 434., 442.,
         450., 458., 466., 474., 482., 490., 498.],
        [506., 514., 522., 530., 538., 546., 554., 562., 570., 578., 586., 594.,
         602., 610., 618., 626., 634., 642., 650., 658., 666., 674., 682., 690.,
         698., 706., 714., 722., 730., 738., 746.],
        [754., 762., 770., 778., 786., 794., 802., 810., 818., 826., 834., 842.,
         850., 858., 866., 874., 882., 890., 898., 906., 914., 922., 930., 938.,
         946., 954., 962., 970., 978., 986., 994.]])

In [87]:
# change the view
z = x.view(124,1)
z

tensor([[ 10.],
        [ 18.],
        [ 26.],
        [ 34.],
        [ 42.],
        [ 50.],
        [ 58.],
        [ 66.],
        [ 74.],
        [ 82.],
        [ 90.],
        [ 98.],
        [106.],
        [114.],
        [122.],
        [130.],
        [138.],
        [146.],
        [154.],
        [162.],
        [170.],
        [178.],
        [186.],
        [194.],
        [202.],
        [210.],
        [218.],
        [226.],
        [234.],
        [242.],
        [250.],
        [258.],
        [266.],
        [274.],
        [282.],
        [290.],
        [298.],
        [306.],
        [314.],
        [322.],
        [330.],
        [338.],
        [346.],
        [354.],
        [362.],
        [370.],
        [378.],
        [386.],
        [394.],
        [402.],
        [410.],
        [418.],
        [426.],
        [434.],
        [442.],
        [450.],
        [458.],
        [466.],
        [474.],
        [482.],
        [490.],
        [498.],
        

In [90]:
x = x[0:10]

In [92]:
x_stacked = torch.stack([x,x,x],dim=1)
x_stacked

tensor([[10., 10., 10.],
        [18., 18., 18.],
        [26., 26., 26.],
        [34., 34., 34.],
        [42., 42., 42.],
        [50., 50., 50.],
        [58., 58., 58.],
        [66., 66., 66.],
        [74., 74., 74.],
        [82., 82., 82.]])

In [95]:
t = torch.zeros(2,1,2,1,2)

In [97]:
t.squeeze().shape

torch.Size([2, 2, 2])

In [104]:
t = torch.zeros(2,2)

In [105]:
t.unsqueeze(dim=0)

tensor([[[0., 0.],
         [0., 0.]]])

In [106]:
t.unsqueeze(dim=-1)

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])

In [107]:
t.unsqueeze(dim=1)

tensor([[[0., 0.]],

        [[0., 0.]]])

In [113]:
x = torch.randn(2,3,5)
x

tensor([[[ 0.3040,  0.5548, -0.3808, -2.0344, -0.4582],
         [-0.8216, -0.9872, -0.7277, -0.8821,  0.7836],
         [-0.5118,  0.2886,  1.4955, -1.8971,  1.1075]],

        [[-1.2975,  0.8059, -0.1022, -0.1190,  1.2819],
         [-0.2171, -0.4647,  1.5958,  0.8569, -0.1194],
         [ 1.8102,  0.2023,  0.9544, -1.4190,  2.3236]]])

In [115]:
torch.permute(x,(2,0,1)).shape # shifts axis 3->1st, 1st-> 2nd, 2nd -> 3rd

torch.Size([5, 2, 3])

# Indexing

In [116]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [117]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [118]:
x[0,0]

tensor([1, 2, 3])

In [119]:
x[0][0]

tensor([1, 2, 3])

In [120]:
x[0][0][2]

tensor(3)

In [126]:
x[:,:,0]

tensor([[1, 4, 7]])

In [127]:
x[:,1]

tensor([[4, 5, 6]])

# Pytorch tensor and Numpy

In [129]:
# numpy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [130]:
# change the value of the array
array += 1

In [131]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [133]:
# Tensor to Numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor.dtype,numpy_tensor.dtype

(torch.float32, dtype('float32'))

## Reproducebility (taking random out of randomness)

In [139]:
# Random seed
torch.manual_seed(42)
torch.randn(7)

tensor([ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082])

In [142]:
torch.manual_seed(17)
torch.randn(7)

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145, -0.6124, -1.1835])

In [146]:
torch.cuda.is_available()

False

## Exercises

In [152]:
torch.manual_seed(0)
tensor = torch.rand(7,7)
tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [154]:
z = torch.matmul(tensor,tensor.T)

In [155]:
z.min(),z.max()

(tensor(0.7881), tensor(3.1500))

In [156]:
z.argmin(),z.argmax()

(tensor(34), tensor(24))

In [157]:
torch.manual_seed(7)
x = torch.rand(size=(1,1,1,10))

y = x.squeeze()


In [158]:
x.shape,y.shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))